### Should get 400 Bad Request when incorrect parameters are posted

POST https://17x7s3xxp2.execute-api.us-west-2.amazonaws.com/latest/orders
Content-Type: application/json

{}

> {%
    client.test("Request failed", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
 %}

### Should get 201 CREATED when correct parameters are posted

POST https://17x7s3xxp2.execute-api.us-west-2.amazonaws.com/latest/orders
Content-Type: application/json

{
  "pizzaId": 2,
  "address": "7 Hauptville Circle, Constantia, 7806"
}

> {%
 client.test("Successful Request", function() {
     client.assert(response.status === 201, "Response status is not 200")
 });

  client.test("Successful Request contains expected body", function() {
     var empty = {};
     client.assert(JSON.stringify(response.body) === JSON.stringify(empty), "Response body is not what is expected: " + JSON.stringify(response.body))
 });
 %}

### should get 404 if delete fails because no entity with that id exists

DELETE https://17x7s3xxp2.execute-api.us-west-2.amazonaws.com/latest/orders/42

> {%
 client.test("Failed Request when id not found", function() {
     client.assert(response.status === 404, "Response status is not 404")
 });
 %}

### should get 204 No Content if delete succeeds

DELETE https://17x7s3xxp2.execute-api.us-west-2.amazonaws.com/latest/orders/2

> {%
 client.test("Successful Request", function() {
     client.assert(response.status === 204, "Response status is not 204")
 });
 %}

### should get 404 if put fails because no entity with that id exists

PUT https://17x7s3xxp2.execute-api.us-west-2.amazonaws.com/latest/orders/42
Content-Type: application/json

{}

> {%
 client.test("Failed Request when id not found", function() {
     client.assert(response.status === 404, "Response status is not 404")
 });
 %}

### should get 200 OK if update succeeds

PUT https://17x7s3xxp2.execute-api.us-west-2.amazonaws.com/latest/orders/2
Content-Type: application/json

{}

> {%
 client.test("Successful Request", function() {
     client.assert(response.status === 200, "Response status is not 200")
 });
 %}

###